spring:
  name: Production
  environment: production
  enabled: true
  datasource:
    url: "jdbc:mysql://localhost:3306/folha_facil"
    username:   Nalcant
    password:   Nm@170604Folha_facil
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: "classpath:db/migration"